import { jsPDF } from 'jspdf';
import { db } from '../db';
import { format } from 'date-fns';
import { analyzeCycleState } from '../logic/cycle';
import { calculateBlossomScore, BlossomScoreResult } from '../logic/blossomScore';
import { calculateSeason } from '../logic/seasons';
import { normalizeSleep, normalizeExercise, normalizeWater } from '../logic/conversions';

interface PDFExportOptions {
  patientName?: string;
  dob?: string;
  sex?: string;
  hn?: string;
}

const COLORS = {
  cream: [250, 244, 237] as [number, number, number],
  pink: [232, 181, 181] as [number, number, number],
  sage: [107, 142, 35] as [number, number, number],
  darkGray: [60, 60, 60] as [number, number, number],
  lightGray: [150, 150, 150] as [number, number, number],
};

const addWatermark = (doc: jsPDF, pageNumber: number, totalPages: number) => {
  doc.setFontSize(8);
  doc.setTextColor(...COLORS.lightGray);
  doc.text(`Page ${pageNumber} of ${totalPages}`, 105, 287, { align: 'center' });
  doc.text('Generated by Blossom PCOS Tracker | Privacy First', 105, 292, { align: 'center' });
};

const addPageBackground = (doc: jsPDF) => {
  doc.setFillColor(...COLORS.cream);
  doc.rect(0, 0, 210, 297, 'F');
};

const addHeader = (doc: jsPDF, title: string, yPosition: number = 20) => {
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.sage);
  doc.text(title, 105, yPosition, { align: 'center' });
  doc.setDrawColor(...COLORS.pink);
  doc.setLineWidth(0.5);
  doc.line(20, yPosition + 3, 190, yPosition + 3);
};

const addSectionHeader = (doc: jsPDF, title: string, yPosition: number) => {
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.sage);
  doc.text(title, 20, yPosition);
  return yPosition + 7;
};

const addText = (doc: jsPDF, text: string, x: number, y: number, options?: {
  fontSize?: number; color?: [number, number, number]; bold?: boolean; align?: 'left' | 'center' | 'right';
}) => {
  doc.setFontSize(options?.fontSize || 10);
  doc.setFont('helvetica', options?.bold ? 'bold' : 'normal');
  doc.setTextColor(...(options?.color || COLORS.darkGray));
  doc.text(text, x, y, { align: options?.align || 'left' });
};

const generateCoverPage = async (doc: jsPDF, options: PDFExportOptions) => {
  addPageBackground(doc);
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.sage);
  doc.text('Blossom Clinical Summary', 105, 60, { align: 'center' });
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...COLORS.darkGray);
  doc.text('Patient-Reported Outcomes & Symptom Trajectory', 105, 70, { align: 'center' });

  doc.setDrawColor(...COLORS.pink);
  doc.setLineWidth(1);
  doc.rect(50, 85, 110, 60, 'S');

  let fieldY = 100;
  const generatedDate = format(new Date(), 'MMMM dd, yyyy');
  addText(doc, `Generated Date: ${generatedDate}`, 60, fieldY);
  fieldY += 12;
  addText(doc, `Patient Name: ${options.patientName || 'Private User'}`, 60, fieldY);

  doc.setFontSize(9);
  doc.setTextColor(...COLORS.lightGray);
  doc.setFont('helvetica', 'italic');
  doc.text('This report contains self-tracked data for clinical discussion purposes only.\nIt is not a medical diagnosis and should be reviewed with a healthcare provider.', 105, 250, { align: 'center', maxWidth: 150 });
  addWatermark(doc, 1, 5);
};

const generateOverviewPage = async (doc: jsPDF, logs: any[], scoreResult: BlossomScoreResult) => {
  doc.addPage();
  addPageBackground(doc);
  addHeader(doc, 'Summary Overview', 20);

  let yPos = 35;
  yPos = addSectionHeader(doc, 'Data Summary', yPos);

  const dateRange = logs.length > 0
    ? `${format(new Date(logs[0].date), 'MMM dd, yyyy')} - ${format(new Date(logs[logs.length - 1].date), 'MMM dd, yyyy')}`
    : 'No data';

  addText(doc, `Total Days Tracked: ${logs.length}`, 25, yPos); yPos += 6;
  addText(doc, `Date Range: ${dateRange}`, 25, yPos); yPos += 12;

  if (logs.length > 0) {
    const season = calculateSeason(scoreResult.score);
    addText(doc, `Current Season: ${season.currentSeason.toUpperCase()}`, 25, yPos, { bold: true, color: COLORS.sage }); yPos += 6;
    addText(doc, `Overall Wellness Score: ${scoreResult.score}/100`, 25, yPos); yPos += 12;

    yPos = addSectionHeader(doc, 'Wellness Score Breakdown (0-100 Scale)', yPos);

    const categories = [
      { name: 'Symptom Wellness', score: scoreResult.symptomFactor || 0 },
      { name: 'Emotional Balance', score: scoreResult.emotionalFactor || 0 },
      { name: 'Self-Care Consistency', score: scoreResult.selfCareFactor || 0 },
      { name: 'Cycle Stability', score: scoreResult.stabilityFactor || 0 },
    ];

    categories.forEach((cat) => {
      addText(doc, cat.name, 25, yPos);
      doc.setFillColor(...COLORS.sage);
      const safeScore = isNaN(cat.score) ? 0 : cat.score;
      doc.rect(80, yPos - 3, (safeScore / 100) * 80, 4, 'F');
      doc.setDrawColor(...COLORS.lightGray);
      doc.rect(80, yPos - 3, 80, 4, 'S');
      addText(doc, `${Math.round(safeScore)}/100`, 165, yPos);
      yPos += 10;
    });
  }
  addWatermark(doc, 2, 5);
};

const generateCycleDetailsPage = (doc: jsPDF, logs: any[]) => {
  doc.addPage();
  addPageBackground(doc);
  addHeader(doc, 'Cycle & Symptom Analysis', 20);

  let yPos = 35;
  yPos = addSectionHeader(doc, 'Menstrual Cycle Pattern', yPos);

  const cycleState = analyzeCycleState(logs);

  if (cycleState.currentDay > 0) {
    addText(doc, `Current Cycle Day: ${cycleState.currentDay}`, 25, yPos); yPos += 6;
    addText(doc, `Cycle Stability: ${cycleState.stabilityScore}/100`, 25, yPos); yPos += 6;
    addText(doc, `Pattern Note: ${cycleState.isLongCycle ? 'Extended Cycles Detected (>35 days)' : 'Standard Length'}`, 25, yPos); yPos += 12;
  } else {
    addText(doc, 'Insufficient cycle data available.', 25, yPos, { color: COLORS.lightGray }); yPos += 12;
  }

  yPos = addSectionHeader(doc, 'Symptom Frequency (Days Reported)', yPos);

  const symptomCounts: Record<string, number> = {
    Acne: 0, Cramps: 0, Bloating: 0, Hirsutism: 0, 'Hair Loss': 0
  };

  logs.forEach(log => {
    if (log.symptoms?.acne && log.symptoms.acne > 0) symptomCounts['Acne']++;
    if (log.symptoms?.cramps && log.symptoms.cramps > 0) symptomCounts['Cramps']++;
    if (log.symptoms?.bloat && log.symptoms.bloat > 0) symptomCounts['Bloating']++;
    if (log.symptoms?.hirsutism && log.symptoms.hirsutism > 0) symptomCounts['Hirsutism']++;
    if (log.symptoms?.hairLoss && log.symptoms.hairLoss > 0) symptomCounts['Hair Loss']++;
  });

  const sortedSymptoms = Object.entries(symptomCounts).sort(([, a], [, b]) => b - a);

  sortedSymptoms.forEach(([symptom, count]) => {
    const percentage = logs.length > 0 ? ((count / logs.length) * 100).toFixed(0) : 0;
    addText(doc, symptom, 25, yPos);

    const barWidth = logs.length > 0 ? (count / logs.length) * 80 : 0;
    doc.setFillColor(...COLORS.sage);
    doc.rect(80, yPos - 3, barWidth, 4, 'F');
    doc.setDrawColor(...COLORS.lightGray);
    doc.rect(80, yPos - 3, 80, 4, 'S');

    addText(doc, `${percentage}% (${count} days)`, 165, yPos);
    yPos += 8;
  });

  addWatermark(doc, 3, 5);
};

const generateLifestylePage = (doc: jsPDF, logs: any[], profile: any) => {
  doc.addPage();
  addPageBackground(doc);
  addHeader(doc, 'Lifestyle & Priorities', 20);

  let yPos = 35;
  yPos = addSectionHeader(doc, 'Patient Priorities', yPos);

  if (profile?.priorities && profile.priorities.length > 0) {
    profile.priorities.forEach((p: string) => {
      const weight = profile.happinessWeights?.[p] || 5;
      addText(doc, `• ${p.replace(/_/g, ' ').toUpperCase()} (Happiness Impact: ${weight}/10)`, 25, yPos);
      yPos += 6;
    });
  } else {
    addText(doc, 'No specific priorities set.', 25, yPos, { color: COLORS.lightGray });
  }
  yPos += 6;

  yPos = addSectionHeader(doc, 'Lifestyle Averages (Wellness Scale 0-10)', yPos);

  let totalExercise = 0, totalSleep = 0, totalDiet = 0;

  logs.forEach(log => {
    totalSleep += normalizeSleep(log.lifestyle?.sleep);
    totalExercise += normalizeExercise(log.lifestyle?.exercise);
    totalDiet += log.lifestyle?.diet === 'balanced' ? 9 : 4;
  });

  const len = logs.length || 1;
  addText(doc, `Average Sleep Wellness: ${(totalSleep / len).toFixed(1)} / 10`, 25, yPos); yPos += 6;
  addText(doc, `Average Movement Wellness: ${(totalExercise / len).toFixed(1)} / 10`, 25, yPos); yPos += 6;
  addText(doc, `Average Diet/Metabolic Wellness: ${(totalDiet / len).toFixed(1)} / 10`, 25, yPos); yPos += 12;

  yPos = addSectionHeader(doc, 'Provider Notes', yPos);
  for (let i = 0; i < 6; i++) {
    doc.setDrawColor(...COLORS.lightGray);
    doc.setLineWidth(0.3);
    doc.line(25, yPos + 2, 185, yPos + 2);
    yPos += 10;
  }

  addWatermark(doc, 4, 5);
};

export const exportClinicalPDF = async (options: PDFExportOptions = {}) => {
  try {
    const logs = await db.logs.orderBy('date').toArray();
    const profile = await db.settings.toCollection().first();

    if (logs.length === 0) {
      throw new Error('No data available to export. Please log some data first.');
    }

    const blossomScoreResult = await calculateBlossomScore(logs);

    const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });

    await generateCoverPage(doc, options);
    await generateOverviewPage(doc, logs, blossomScoreResult);
    generateCycleDetailsPage(doc, logs);
    generateLifestylePage(doc, logs, profile);

    const fileName = `Blossom-Clinical-Summary-${format(new Date(), 'yyyy-MM-dd')}.pdf`;
    doc.save(fileName);

    return { success: true, fileName };
  } catch (error) {
    console.error('PDF Export Error:', error);
    throw error;
  }
};
