import { jsPDF } from 'jspdf';
import html2canvas from 'html2canvas';
import { db } from '../db';
import { format } from 'date-fns';
import { analyzeHistory } from '../logic/cycle';
import { calculateBlossomScore } from '../logic/blossomScore';
import { calculateSeason } from '../logic/seasons';

interface PDFExportOptions {
  includeCharts?: boolean;
  patientName?: string;
  dob?: string;
  sex?: string;
  hn?: string;
}

const COLORS = {
  cream: [250, 244, 237] as [number, number, number],
  pink: [232, 181, 181] as [number, number, number],
  sage: [107, 142, 35] as [number, number, number],
  darkGray: [60, 60, 60] as [number, number, number],
  lightGray: [150, 150, 150] as [number, number, number],
  black: [0, 0, 0] as [number, number, number],
};

const addWatermark = (doc: jsPDF, pageNumber: number, totalPages: number) => {
  doc.setFontSize(8);
  doc.setTextColor(...COLORS.lightGray);
  doc.text(`Page ${pageNumber} of ${totalPages}`, 105, 287, { align: 'center' });
  doc.text('Generated by Blossom PCOS Tracker', 105, 292, { align: 'center' });
};

const addPageBackground = (doc: jsPDF) => {
  doc.setFillColor(...COLORS.cream);
  doc.rect(0, 0, 210, 297, 'F');
};

const addHeader = (doc: jsPDF, title: string, yPosition: number = 20) => {
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.sage);
  doc.text(title, 105, yPosition, { align: 'center' });

  doc.setDrawColor(...COLORS.pink);
  doc.setLineWidth(0.5);
  doc.line(20, yPosition + 3, 190, yPosition + 3);
};

const addSectionHeader = (doc: jsPDF, title: string, yPosition: number) => {
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.sage);
  doc.text(title, 20, yPosition);

  return yPosition + 7;
};

const addText = (doc: jsPDF, text: string, x: number, y: number, options?: {
  fontSize?: number;
  color?: [number, number, number];
  bold?: boolean;
  align?: 'left' | 'center' | 'right';
}) => {
  doc.setFontSize(options?.fontSize || 10);
  doc.setFont('helvetica', options?.bold ? 'bold' : 'normal');
  doc.setTextColor(...(options?.color || COLORS.darkGray));
  doc.text(text, x, y, { align: options?.align || 'left' });
};

const addBlankField = (doc: jsPDF, label: string, x: number, y: number, width: number = 60) => {
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...COLORS.darkGray);
  doc.text(label, x, y);

  doc.setDrawColor(...COLORS.lightGray);
  doc.setLineWidth(0.3);
  const labelWidth = doc.getTextWidth(label);
  doc.line(x + labelWidth + 2, y + 0.5, x + labelWidth + width, y + 0.5);
};

const generateCoverPage = async (doc: jsPDF, options: PDFExportOptions) => {
  addPageBackground(doc);

  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.sage);
  doc.text('Blossom Clinical Summary', 105, 60, { align: 'center' });

  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...COLORS.darkGray);
  doc.text('Patient-Reported Outcomes & Symptom Trajectory', 105, 70, { align: 'center' });

  doc.setDrawColor(...COLORS.pink);
  doc.setLineWidth(1);
  doc.rect(50, 85, 110, 80);

  let fieldY = 100;
  addBlankField(doc, 'Patient Name:', 60, fieldY, 80);
  fieldY += 12;
  addBlankField(doc, 'Date of Birth:', 60, fieldY, 80);
  fieldY += 12;
  addBlankField(doc, 'Sex:', 60, fieldY, 80);
  fieldY += 12;
  addBlankField(doc, 'Hospital Number:', 60, fieldY, 80);
  fieldY += 12;
  addBlankField(doc, 'Generated Date:', 60, fieldY, 80);

  doc.setFontSize(10);
  doc.setTextColor(...COLORS.darkGray);
  const generatedDate = format(new Date(), 'MMMM dd, yyyy');
  doc.text(generatedDate, 148, fieldY);

  doc.setFontSize(9);
  doc.setTextColor(...COLORS.lightGray);
  doc.setFont('helvetica', 'italic');
  const disclaimer = 'This report contains self-tracked data for clinical discussion purposes only.\nIt is not a medical diagnosis and should be reviewed with a healthcare provider.';
  doc.text(disclaimer, 105, 250, { align: 'center', maxWidth: 150 });

  addWatermark(doc, 1, 5);
};

const generateOverviewPage = async (doc: jsPDF, logs: any[], priorities: any[]) => {
  doc.addPage();
  addPageBackground(doc);
  addHeader(doc, 'Summary Overview', 20);

  let yPos = 35;

  yPos = addSectionHeader(doc, 'Data Summary', yPos);

  const dateRange = logs.length > 0
    ? `${format(new Date(logs[0].date), 'MMM dd, yyyy')} - ${format(new Date(logs[logs.length - 1].date), 'MMM dd, yyyy')}`
    : 'No data';

  addText(doc, `Total Days Tracked: ${logs.length}`, 25, yPos);
  yPos += 6;
  addText(doc, `Date Range: ${dateRange}`, 25, yPos);
  yPos += 6;

  const latestLog = logs[logs.length - 1];
  if (latestLog) {
    const season = calculateSeason(latestLog);
    addText(doc, `Current Season: ${season.name}`, 25, yPos);
    yPos += 6;

    const blossomScore = calculateBlossomScore({
      symptoms: latestLog.symptoms || {},
      mood: latestLog.mood || 5,
      energy: latestLog.energy || 5,
      sleep: latestLog.sleep || 5,
    });
    addText(doc, `Current Wellness Score: ${blossomScore.total}/100`, 25, yPos);
    yPos += 10;
  }

  yPos = addSectionHeader(doc, 'Wellness Score Breakdown', yPos);

  if (latestLog) {
    const blossomScore = calculateBlossomScore({
      symptoms: latestLog.symptoms || {},
      mood: latestLog.mood || 5,
      energy: latestLog.energy || 5,
      sleep: latestLog.sleep || 5,
    });

    const categories = [
      { name: 'Physical Health', score: blossomScore.physical },
      { name: 'Mental Wellbeing', score: blossomScore.mental },
      { name: 'Hormonal Balance', score: blossomScore.hormonal },
      { name: 'Lifestyle Factors', score: blossomScore.lifestyle },
    ];

    categories.forEach((cat) => {
      addText(doc, cat.name, 25, yPos);

      doc.setFillColor(...COLORS.sage);
      doc.rect(80, yPos - 3, (cat.score / 25) * 80, 4, 'F');

      doc.setDrawColor(...COLORS.lightGray);
      doc.rect(80, yPos - 3, 80, 4);

      addText(doc, `${cat.score}/25`, 165, yPos);

      yPos += 8;
    });
  }

  yPos += 5;
  yPos = addSectionHeader(doc, 'Current Bloom Status', yPos);

  if (latestLog) {
    const blossomScore = calculateBlossomScore({
      symptoms: latestLog.symptoms || {},
      mood: latestLog.mood || 5,
      energy: latestLog.energy || 5,
      sleep: latestLog.sleep || 5,
    });

    let bloomStatus = 'Budding';
    if (blossomScore.total >= 75) bloomStatus = 'Full Bloom';
    else if (blossomScore.total >= 50) bloomStatus = 'Blooming';
    else if (blossomScore.total >= 25) bloomStatus = 'Growing';

    addText(doc, bloomStatus, 25, yPos, { fontSize: 12, bold: true, color: COLORS.sage });
    yPos += 6;
    addText(doc, `Overall wellness trajectory based on tracked symptoms and lifestyle factors.`, 25, yPos, { fontSize: 9, color: COLORS.lightGray });
  }

  addWatermark(doc, 2, 5);
};

const generatePrioritiesPage = (doc: jsPDF, priorities: any[], logs: any[]) => {
  doc.addPage();
  addPageBackground(doc);
  addHeader(doc, 'Health Priorities & Impact', 20);

  let yPos = 35;

  addText(doc, 'These areas represent what matters most to the patient, guiding personalized care.', 20, yPos, { fontSize: 9, color: COLORS.lightGray });
  yPos += 10;

  if (priorities.length === 0) {
    addText(doc, 'No priorities have been set yet.', 25, yPos, { color: COLORS.lightGray });
  } else {
    doc.setDrawColor(...COLORS.pink);
    doc.setLineWidth(0.3);

    doc.setFillColor(...COLORS.sage);
    doc.rect(20, yPos, 170, 8, 'F');

    doc.setTextColor(255, 255, 255);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.text('Priority Area', 25, yPos + 5);
    doc.text('Happiness Impact', 120, yPos + 5);

    yPos += 8;

    priorities.forEach((priority, index) => {
      if (yPos > 270) {
        doc.addPage();
        addPageBackground(doc);
        yPos = 30;
      }

      if (index % 2 === 0) {
        doc.setFillColor(245, 240, 235);
        doc.rect(20, yPos, 170, 8, 'F');
      }

      doc.setTextColor(...COLORS.darkGray);
      doc.setFont('helvetica', 'normal');
      doc.text(priority.name, 25, yPos + 5);

      const impact = priority.happiness_impact || 0;
      doc.text(`${impact}/10`, 120, yPos + 5);

      const barWidth = (impact / 10) * 50;
      doc.setFillColor(...COLORS.pink);
      doc.rect(135, yPos + 1, barWidth, 6, 'F');

      doc.setDrawColor(...COLORS.lightGray);
      doc.rect(135, yPos + 1, 50, 6);

      yPos += 8;
    });
  }

  addWatermark(doc, 3, 5);
};

const generateCycleDetailsPage = (doc: jsPDF, logs: any[]) => {
  doc.addPage();
  addPageBackground(doc);
  addHeader(doc, 'Cycle & Symptom Analysis', 20);

  let yPos = 35;

  yPos = addSectionHeader(doc, 'Menstrual Cycle Pattern', yPos);

  const analysis = analyzeHistory(logs);

  if (analysis.cycleLengths.length > 0) {
    addText(doc, `Average Cycle Length: ${Math.round(analysis.avgCycleLength)} days`, 25, yPos);
    yPos += 6;
    addText(doc, `Total Cycles Tracked: ${analysis.cycleLengths.length}`, 25, yPos);
    yPos += 6;
    addText(doc, `Cycle Stability: ${analysis.stability}`, 25, yPos);
    yPos += 6;
    addText(doc, `Pattern: ${analysis.pattern}`, 25, yPos);
    yPos += 10;
  } else {
    addText(doc, 'Insufficient cycle data available.', 25, yPos, { color: COLORS.lightGray });
    yPos += 10;
  }

  yPos = addSectionHeader(doc, 'Symptom Frequency', yPos);

  const symptomCounts: Record<string, number> = {};
  logs.forEach(log => {
    const symptoms = log.symptoms || {};
    Object.keys(symptoms).forEach(symptom => {
      if (symptoms[symptom]) {
        symptomCounts[symptom] = (symptomCounts[symptom] || 0) + 1;
      }
    });
  });

  const sortedSymptoms = Object.entries(symptomCounts)
    .sort(([, a], [, b]) => b - a)
    .slice(0, 10);

  if (sortedSymptoms.length > 0) {
    sortedSymptoms.forEach(([symptom, count]) => {
      const percentage = ((count / logs.length) * 100).toFixed(0);

      addText(doc, symptom.replace(/([A-Z])/g, ' $1').trim(), 25, yPos);

      const barWidth = (count / logs.length) * 100;
      doc.setFillColor(...COLORS.sage);
      doc.rect(80, yPos - 3, barWidth, 4, 'F');

      doc.setDrawColor(...COLORS.lightGray);
      doc.rect(80, yPos - 3, 100, 4);

      addText(doc, `${percentage}% (${count} days)`, 185, yPos, { align: 'right' });

      yPos += 7;

      if (yPos > 270) {
        doc.addPage();
        addPageBackground(doc);
        yPos = 30;
      }
    });
  } else {
    addText(doc, 'No symptom data available.', 25, yPos, { color: COLORS.lightGray });
  }

  addWatermark(doc, 4, 5);
};

const generateLifestylePage = (doc: jsPDF, logs: any[]) => {
  doc.addPage();
  addPageBackground(doc);
  addHeader(doc, 'Lifestyle Factors & Clinical Notes', 20);

  let yPos = 35;

  yPos = addSectionHeader(doc, 'Lifestyle Patterns', yPos);

  let totalExercise = 0;
  let exerciseDays = 0;
  let totalHydration = 0;
  let hydrationDays = 0;
  let totalSleep = 0;
  let sleepDays = 0;

  logs.forEach(log => {
    if (log.exercise !== undefined && log.exercise !== null) {
      totalExercise += log.exercise;
      exerciseDays++;
    }
    if (log.hydration !== undefined && log.hydration !== null) {
      totalHydration += log.hydration;
      hydrationDays++;
    }
    if (log.sleep !== undefined && log.sleep !== null) {
      totalSleep += log.sleep;
      sleepDays++;
    }
  });

  if (exerciseDays > 0) {
    const avgExercise = (totalExercise / exerciseDays).toFixed(1);
    addText(doc, `Average Exercise: ${avgExercise}/10`, 25, yPos);
    yPos += 6;
  }

  if (hydrationDays > 0) {
    const avgHydration = (totalHydration / hydrationDays).toFixed(1);
    addText(doc, `Average Hydration: ${avgHydration}/10`, 25, yPos);
    yPos += 6;
  }

  if (sleepDays > 0) {
    const avgSleep = (totalSleep / sleepDays).toFixed(1);
    addText(doc, `Average Sleep Quality: ${avgSleep}/10`, 25, yPos);
    yPos += 10;
  }

  yPos = addSectionHeader(doc, 'Correlations & Insights', yPos);

  doc.setFillColor(245, 240, 235);
  doc.setDrawColor(...COLORS.pink);
  doc.roundedRect(25, yPos, 160, 30, 3, 3, 'FD');

  addText(doc, 'Key Observations:', 30, yPos + 8, { bold: true });
  addText(doc, 'Symptom patterns and lifestyle correlations are best discussed', 30, yPos + 14, { fontSize: 9 });
  addText(doc, 'with your healthcare provider for personalized interpretation.', 30, yPos + 19, { fontSize: 9 });

  yPos += 40;

  yPos = addSectionHeader(doc, 'Provider Notes', yPos);

  for (let i = 0; i < 8; i++) {
    doc.setDrawColor(...COLORS.lightGray);
    doc.setLineWidth(0.3);
    doc.line(25, yPos + 2, 185, yPos + 2);
    yPos += 10;
  }

  yPos += 10;

  doc.setFillColor(255, 250, 240);
  doc.setDrawColor(...COLORS.sage);
  doc.roundedRect(20, yPos, 170, 25, 3, 3, 'FD');

  doc.setFontSize(9);
  doc.setFont('helvetica', 'italic');
  doc.setTextColor(...COLORS.darkGray);
  const finalDisclaimer = [
    'IMPORTANT DISCLAIMER:',
    'This document contains patient self-reported data and is intended solely for clinical discussion.',
    'It does not constitute medical advice, diagnosis, or treatment recommendations.',
    'All clinical decisions should be made by qualified healthcare professionals.'
  ];

  let disclaimerY = yPos + 6;
  finalDisclaimer.forEach(line => {
    doc.text(line, 105, disclaimerY, { align: 'center', maxWidth: 160 });
    disclaimerY += 4;
  });

  doc.setFontSize(8);
  doc.setFont('helvetica', 'italic');
  doc.setTextColor(...COLORS.lightGray);
  doc.text('Founder: Ritika Yamdagni | Privacy & Terms: blossom@yamdagni.com', 105, 280, { align: 'center' });

  addWatermark(doc, 5, 5);
};

export const exportClinicalPDF = async (options: PDFExportOptions = {}) => {
  try {
    const logs = await db.logs.orderBy('date').toArray();
    const priorities = [];

    if (logs.length === 0) {
      throw new Error('No data available to export. Please track some symptoms first.');
    }

    const doc = new jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: 'a4',
    });

    await generateCoverPage(doc, options);
    await generateOverviewPage(doc, logs, priorities);
    generatePrioritiesPage(doc, priorities, logs);
    generateCycleDetailsPage(doc, logs);
    generateLifestylePage(doc, logs);

    const fileName = `Blossom-Clinical-Summary-${format(new Date(), 'yyyy-MM-dd')}.pdf`;
    doc.save(fileName);

    return { success: true, fileName };
  } catch (error) {
    console.error('PDF Export Error:', error);
    throw error;
  }
};
