/*
  # Add bot_token to profiles

  ## Overview
  Adds a `bot_token` column to the `profiles` table to support secure
  token-based authentication for the Telegram bot integration.

  ## Changes
  - `profiles`: New column `bot_token` (text, nullable)
    - Stores a 32-character hex token generated by the app
    - Used by the Telegram bot to verify the user is authenticated
    - No health data is stored here — token only

  ## Security
  - Existing RLS policies already allow authenticated users to update their own row
  - No additional policies needed
*/

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'profiles' AND column_name = 'bot_token'
  ) THEN
    ALTER TABLE public.profiles ADD COLUMN bot_token text;
  END IF;
END $$;
